
version: 2

models:
  - name: stg_customer
    description: "Model with all customer details"
    columns:
      - name: CustomerName
        description: "Name of the customer"
        data_tests:
          - unique
          - not_null
      - name: StateProvinceCode
        description: "Province Code"
        data_tests:
          - unique
          - not_null
